server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yebixing/sz63config.git
  rabbitmq:
    host: 192.168.66.134
management: #暴露触发消息总线的地址, 发送一个post http://localhost:12000/actuator/bus-refresh
  endpoints:
    web:
      exposure:
        include: bus-refresh   #bus-refresh可以随意修改